### ISSUE TITLE
Clear a patient from the test queue

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#57] opened 2020-10-16 16:08 UTC
As a person administering tests, I want to be able to remove someone from the test queue, so that I can remove someone I accidentally added or who's test was canceled. 

## Acceptance Criteria

Updated: Nov 2, 2020
- [x] When a user deletes a test remove the test from the queue and archive the incomplete test
~~- [ ] Animate the test away and animate sliding up the other testing cards (if this ends up being time consuming let's talk about it/skip it)~~ (out of scope, move to the styles ticket)

**Comment by hmyers-cms** [comment] 2020-10-16 16:13
The prototype is now updated to include this interaction (sans animation because I can't do that in Invision)

**Comment by pete-gov** [comment] 2020-11-03 16:44
Confirmed this is done in the coded prototype by clicking the X button and the code is in `main` - closing.

![remove-from-queue](https://user-images.githubusercontent.com/51794651/98014664-f02c5000-1dc9-11eb-8e2f-b09d8148c404.gif)

**Closed as completed by pete-gov** 2020-11-03 16:44 UTC
Labels: Engineering, Design, MVP
